- name: apache
  ip: 192.168.1.8
  net: ex-swarm
- name: plex
  ip: 192.168.1.10
  net: ex-swarm
- name: qbittorrent
  ip: 192.168.1.11
  net: ex-swarm
- name: ipfs
  ip: 192.168.1.12
  net: ex-swarm
